# Generated by Django 6.0.1 on 2026-01-31 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_doctoravailability_options_and_more'),
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(max_length=200)),
                ('is_recurring', models.BooleanField(default=False, help_text='Repeats every year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ernakulam Pet Hospital', max_length=200)),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='18:00')),
                ('weekly_off_days', models.CharField(default='6', help_text='Comma-separated day numbers (0=Monday, 6=Sunday)', max_length=20)),
                ('slot_duration', models.IntegerField(default=30, help_text='Appointment slot duration in minutes')),
                ('emergency_enabled', models.BooleanField(default=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('avg_consultation_time', models.IntegerField(default=15, help_text='Average consultation time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Settings',
                'verbose_name_plural': 'Clinic Settings',
            },
        ),
        migrations.CreateModel(
            name='GroomingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('BATHING', 'Bathing'), ('HAIR_TRIMMING', 'Hair Trimming'), ('NAIL_CLIPPING', 'Nail Clipping'), ('FULL_GROOMING', 'Full Grooming Package'), ('EAR_CLEANING', 'Ear Cleaning'), ('TEETH_CLEANING', 'Teeth Cleaning'), ('DESHEDDING', 'De-shedding Treatment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('small_pet_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medium_pet_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('large_pet_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QueueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('current_token', models.IntegerField(default=0)),
                ('last_called_token', models.IntegerField(default=0)),
                ('total_appointments', models.IntegerField(default=0)),
                ('completed_appointments', models.IntegerField(default=0)),
                ('avg_wait_time', models.IntegerField(default=0, help_text='Average wait time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Queue Statuses',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='When patient checked in', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_position',
            field=models.IntegerField(blank=True, help_text='Current position in queue', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.IntegerField(blank=True, help_text='Daily token number', null=True),
        ),
        migrations.CreateModel(
            name='DoctorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy with Patient'), ('ON_LEAVE', 'On Leave'), ('BREAK', 'On Break'), ('EMERGENCY', 'Handling Emergency'), ('OFF_DUTY', 'Off Duty')], default='OFF_DUTY', max_length=20)),
                ('status_message', models.CharField(blank=True, help_text='Custom status message', max_length=200)),
                ('leave_start', models.DateField(blank=True, null=True)),
                ('leave_end', models.DateField(blank=True, null=True)),
                ('leave_reason', models.CharField(blank=True, max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_doctor_status', to='appointments.appointment')),
                ('veterinarian', models.OneToOneField(limit_choices_to={'role': 'VET'}, on_delete=django.db.models.deletion.CASCADE, related_name='current_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Doctor Statuses',
            },
        ),
        migrations.CreateModel(
            name='GroomingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_size', models.CharField(choices=[('SMALL', 'Small (< 10 kg)'), ('MEDIUM', 'Medium (10-25 kg)'), ('LARGE', 'Large (> 25 kg)')], default='MEDIUM', max_length=10)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('token_number', models.IntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special grooming instructions')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grooming_appointments_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_appointments_as_owner', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_appointments', to='medical_records.pet')),
                ('services', models.ManyToManyField(related_name='appointments', to='appointments.groomingservice')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
