# Generated by Django 5.1.15 on 2026-01-28 04:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(choices=[('RINGWORM', 'Ringworm'), ('MANGE', 'Mange (Scabies)'), ('DERMATITIS', 'Dermatitis'), ('HOT_SPOT', 'Hot Spot'), ('ALLERGY', 'Allergic Reaction'), ('FUNGAL', 'Fungal Infection'), ('BACTERIAL', 'Bacterial Infection'), ('FLEA', 'Flea Allergy'), ('ECZEMA', 'Eczema'), ('HEALTHY', 'Healthy/No Disease Detected')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('home_care', models.TextField(help_text='What owners can do at home')),
                ('medical_treatment', models.TextField(help_text='Professional treatment options')),
                ('prevention', models.TextField(help_text='Prevention tips')),
                ('recovery_time', models.CharField(max_length=200)),
                ('contagious', models.BooleanField(default=False)),
                ('external_resources', models.TextField(blank=True, help_text='Links to additional information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['disease'],
            },
        ),
        migrations.CreateModel(
            name='AIModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_predictions', models.IntegerField(default=0)),
                ('accurate_predictions', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('average_processing_time', models.FloatField(default=0.0, help_text='In seconds')),
                ('disease_accuracy_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'AI model metrics',
                'ordering': ['-date'],
                'unique_together': {('model_version', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SkinDiseaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai_diagnosis/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('description', models.TextField(blank=True, help_text='Any additional details about the condition')),
                ('affected_area', models.CharField(blank=True, help_text='Body part affected', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analysis'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_disease_images', to='medical_records.pet')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_disease', models.CharField(choices=[('RINGWORM', 'Ringworm'), ('MANGE', 'Mange (Scabies)'), ('DERMATITIS', 'Dermatitis'), ('HOT_SPOT', 'Hot Spot'), ('ALLERGY', 'Allergic Reaction'), ('FUNGAL', 'Fungal Infection'), ('BACTERIAL', 'Bacterial Infection'), ('FLEA', 'Flea Allergy'), ('ECZEMA', 'Eczema'), ('HEALTHY', 'Healthy/No Disease Detected')], max_length=50)),
                ('confidence_score', models.FloatField(help_text='Confidence score between 0 and 1')),
                ('confidence_level', models.CharField(choices=[('VERY_LOW', 'Very Low (< 40%)'), ('LOW', 'Low (40-60%)'), ('MEDIUM', 'Medium (60-80%)'), ('HIGH', 'High (80-95%)'), ('VERY_HIGH', 'Very High (> 95%)')], max_length=20)),
                ('alternative_diagnosis_1', models.CharField(blank=True, choices=[('RINGWORM', 'Ringworm'), ('MANGE', 'Mange (Scabies)'), ('DERMATITIS', 'Dermatitis'), ('HOT_SPOT', 'Hot Spot'), ('ALLERGY', 'Allergic Reaction'), ('FUNGAL', 'Fungal Infection'), ('BACTERIAL', 'Bacterial Infection'), ('FLEA', 'Flea Allergy'), ('ECZEMA', 'Eczema'), ('HEALTHY', 'Healthy/No Disease Detected')], max_length=50)),
                ('alternative_confidence_1', models.FloatField(blank=True, null=True)),
                ('alternative_diagnosis_2', models.CharField(blank=True, choices=[('RINGWORM', 'Ringworm'), ('MANGE', 'Mange (Scabies)'), ('DERMATITIS', 'Dermatitis'), ('HOT_SPOT', 'Hot Spot'), ('ALLERGY', 'Allergic Reaction'), ('FUNGAL', 'Fungal Infection'), ('BACTERIAL', 'Bacterial Infection'), ('FLEA', 'Flea Allergy'), ('ECZEMA', 'Eczema'), ('HEALTHY', 'Healthy/No Disease Detected')], max_length=50)),
                ('alternative_confidence_2', models.FloatField(blank=True, null=True)),
                ('alternative_diagnosis_3', models.CharField(blank=True, choices=[('RINGWORM', 'Ringworm'), ('MANGE', 'Mange (Scabies)'), ('DERMATITIS', 'Dermatitis'), ('HOT_SPOT', 'Hot Spot'), ('ALLERGY', 'Allergic Reaction'), ('FUNGAL', 'Fungal Infection'), ('BACTERIAL', 'Bacterial Infection'), ('FLEA', 'Flea Allergy'), ('ECZEMA', 'Eczema'), ('HEALTHY', 'Healthy/No Disease Detected')], max_length=50)),
                ('alternative_confidence_3', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('recommended_actions', models.TextField(blank=True)),
                ('urgency_level', models.CharField(choices=[('ROUTINE', 'Routine Check-up'), ('SOON', 'Schedule Soon'), ('URGENT', 'Urgent - Book Immediately'), ('EMERGENCY', 'Emergency - Seek Immediate Care')], default='ROUTINE', max_length=20)),
                ('vet_confirmed', models.BooleanField(blank=True, null=True)),
                ('vet_diagnosis', models.CharField(blank=True, choices=[('RINGWORM', 'Ringworm'), ('MANGE', 'Mange (Scabies)'), ('DERMATITIS', 'Dermatitis'), ('HOT_SPOT', 'Hot Spot'), ('ALLERGY', 'Allergic Reaction'), ('FUNGAL', 'Fungal Infection'), ('BACTERIAL', 'Bacterial Infection'), ('FLEA', 'Flea Allergy'), ('ECZEMA', 'Eczema'), ('HEALTHY', 'Healthy/No Disease Detected')], max_length=50)),
                ('vet_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by_vet', models.ForeignKey(blank=True, limit_choices_to={'role': 'VET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_diagnoses', to=settings.AUTH_USER_MODEL)),
                ('skin_disease_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_result', to='ai_diagnosis.skindiseaseimage')),
            ],
            options={
                'verbose_name_plural': 'Diagnosis results',
                'ordering': ['-created_at'],
            },
        ),
    ]
